Should catching multiple exception types in an "except" increase complexity?

Handle nested functions.
